name: Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  checks:
    runs-on: ubuntu-latest
  
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dask-optuna
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .

    - name: Install test dependencies
      run: python -m pip install pytest

    - name: List packages
      run: python -m pip list

    - name: Run tests
      run: python -m pytest -v dask_optuna